### ISSUE TITLE
Saving video output does not work. 

### ISSUE THREAD

**Issue by mattdoescode** [tensorturtle/classy-sort-yolov5#10] opened 2021-12-06 04:45 UTC
Setting --save-img to true when processing a webcam input causes :

Traceback (most recent call last):
  File "classy_track.py", line 318, in <module>
    detect(args)
  File "classy_track.py", line 256, in detect
    fps = vid_cap.get(cv2.CAP_PROP_FPS)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by tensorturtle** [comment] 2021-12-06 14:59
Are you having a problem only when `--save-img`? Are you able to see the inference result with `--view-img`?

**Comment by mattdoescode** [comment] 2021-12-06 16:13
Only having the problem with --save-img. I am able to view the video feed with --view-img for 1 frame and then the program crashes (works just fine when not using save-img).

**Comment by tensorturtle** [comment] 2021-12-07 03:28
Could you tell me exactly what path you set as the `--save-img` path?

Please see [this article](https://www.pyimagesearch.com/2016/12/26/opencv-resolving-nonetype-errors/) for more debugging possibilities.

**Comment by mattdoescode** [comment] 2021-12-07 18:03
I've been setting it is to "True". The save path is "inference\output". I'll look into the article. thank you!

The bug seems to come from this line:  **_for frame_idx, (path, img, im0s, vid_cap) in enumerate(dataset):_** 
In class Loadstreams **cap = cv2.VideoCapture(eval(s) if s.isnumeric() else s)** works just fine. But when we try to enumerate it when it breaks.

**Comment by tensorturtle** [comment] 2021-12-08 05:41
I'm still not sure why this bug only happens when `--save-img` is True,
but if the problem is with cv2.VideoCapture, then try running the basic OpenCV webcam test script [from this link](https://www.geeksforgeeks.org/python-opencv-capture-video-from-camera/).

Also, it could be helpful if you cold tell me all the details about what computer / camera you're using.

**Comment by mattdoescode** [comment] 2021-12-08 05:46
I'm pretty sure I've figured it out. I'll post the solution tomorrow. Thank you so much for the help here!

**Comment by tensorturtle** [comment] 2021-12-08 09:46
Very glad to hear. Thank you.

**Comment by mattdoescode** [comment] 2021-12-08 17:58
Got it... and I feel really silly (I'm a novice programmer). The video recorder was never being passed back. 

 [In datasets.py ](https://github.com/tensorturtle/classy-sort-yolov5/blob/main/yolov5/utils/datasets.py) line 324-> return img_path, img, img0, None. I changed None to be self.cap and added a newline on line 280 self.cap = cap 

This might break some aspects of the script but for my usage, it works. I'll play with this and eventually make a pull request.

**Closed as completed** 2021-12-08 17:58 UTC
